# Business Analytics

**Magister en Control de Gestión**

**Semestre Otoño 2022**

**Profesor: Diego Beas**
    
**Ayudantes: Francisco Robles - Freddy Acuña - Nicolás Miras**

---
# Ayudantía 1 : Introducción a Python

## 1. Trabajando en Jupyter:
**Insert** -> Cell Above (Abajo)


**Insert** -> Cell Below (Arriba)

**Edit** -> Delete Cells (Borrar Celdas)

**Code:** Correr Código y Dejar Notas

**Markdown:** Escribir Mensajes. Entre más "#" hayan, más chica se hace la letra.

***RECUERDEN SIEMPRE GUARDAR LOS AVANCES***

In [5]:
# Utilizando "gato" podemos escribir comentarios en una línea de código
print("Hola Mundo")

Hola Mundo


In [6]:
print(":)") # También dejar comentarios en la misma línea de código

:)


## 2. Función Print:
La función Print lo que hace sencillamente es imprimir en pantalla lo que nosotros le indiquemos como argumento:

In [7]:
print("Hola esto es una cadena de texto")

Hola esto es una cadena de texto


Ejecutando este código estamos llamando a la función predefinida print y mostrara en pantalla «Hola esto es una cadena de texto». Puesto que la función toma como argumento, el texto que está entre comillas.

### Evitar los errores de sintaxis:
1. El texto siempre debe estar entre *comillas* porque sino se interpretará a las palabras como algún objeto que por supuesto no existe!! y nos dará un *Error de sintaxis!*
 

2. Siempre se debe respetar la Sintaxis de las funciones en python colocando luego de ella los paréntesis. Aunque no se le indique ningún argumento, debe llevar los paréntesis que serán los que indiquen que es una función!. Por ejemplo: print() , esto no imprimirá nada, pero no nos dará ningún error.

In [8]:
# Tambien podemos imprimir números
print(123)

123


In [9]:
# También se pueden hacer calculos
1+2+3*10/2

18.0

## 3. Declarando variables:
 En python al declarar una variable no necesitamos especificar el tipo de dato que vamos a almacenar en ella como, si es necesario en otros lenguajes de programación (VBA). A continuación declararemos 4 variables de la siguiente manera:

In [37]:
Var_1 = "BA es el mejor ramo para sufrir" # Varible del tipo texto (str)
Var_2 = 18  # Varible del tipo entero (int)
Var_3 = 98.12 # Varible del tipo float
Var_4 = True # Varible del tipo boolean
Var_5 = 1+2*3

BolaDeNieves = 5 # Se le puede asignar cualquier nombre a las variables

In [41]:
# Del mismo modo también podemos imprimir las variables! De 2 formas:
print(Var_1) # No indica si la variable es string o no
Var_1 # Indica si la variable es string o no

BA es el mejor ramo para sufrir


'BA es el mejor ramo para sufrir'

In [40]:
print (Var_5)
Var_5

7


7

### Función Print Type
Si ya has declarado las funciones anteriores puedes saber su tipo utilizando la función predefinida **Type()** que nos permitirá saber la naturaleza de una variable en un momento en específico

#### Hay 3 tipos más comunes de variables:

> ##### Numéricas : Almacenan números, dentro de ellas podemos encontrar subtipos Int, float, complex

> ##### Texto: Son las clásicas variables que almacenan cadenas de texto.

> ##### Booleanas: Almacenan un valor «True» o «False«.

In [42]:
print (type(Var_1))
print (type(Var_2))
print (type(Var_3))
print (type(Var_4))
print(type(BolaDeNieves))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>
<class 'int'>


### 4. Librerías:

#### Cargar librerías
1. Para importar una librería se usa la orden **import**.

2. Se puede usar la palabra **as** para importar el módulo o funciones con otros nombre para abreviar o convención.

3. En caso de necesitar solo ciertas funciones y no cargar todo, ya que esto resulta inconveniente en grandes modulos o librerias, existe la orden **from** librería **import** función.

A continuación cargaremos la libreria **numpy** con el nombre **np**.

NumPy es una libreria de Python, que le agrega mayor soporte para vectores y matrices:

In [43]:
# Importamos numpy

import numpy as np

### 5.  Numpy
#### 5.1 ARRAY (ARREGLOS)
A continuación generaremos un arreglo con los numeros del 1 al 9, utlizando la funcion array de numpy. 

In [14]:
arreglo = np.array([1,2,3,4,5,6,7,8,9])
arreglo

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Ejercicios Básicos:

* 5.1 Genere la siguiente matriz A y defina su composición:

    $$
    A = \begin{pmatrix}
    5 & 8 & -4 \\
    6 & 9 & -5\\
    4 & 7 & -2
    \end{pmatrix}
    $$

Utilizaremos la función **reshape(filas,columnas)** que permite generar una matriz según el array (arreglo) que ejecutemos. y **shape** sirve para ver su composición.

In [44]:
Matriz_A = np.array([5, 8, -4, 6, 9, -5, 4, 7, -2]).reshape(3,3)

In [61]:
Matriz_A

array([[ 5,  8, -4],
       [ 6,  9, -5],
       [ 4,  7, -2]])

In [80]:
Matriz_A.shape

(3, 3)

* 5.2 Calcule la matriz Inversa de la matriz A y la Traspuesta

Para calcular la inversa de la matriz A necesitamos la función **"inv"** de "Numpy algebra lineal" (numpy.linalg)

In [47]:
from numpy.linalg import inv  # cargamos la funcion inv desde numpy.linalg

In [48]:
#Calculamos la inversa 
inv(Matriz_A)

array([[-5.66666667,  4.        ,  1.33333333],
       [ 2.66666667, -2.        , -0.33333333],
       [-2.        ,  1.        ,  1.        ]])

In [56]:
# Calculamos la Matriz Transpuesta: 2 ways

Matriz_A.T

#np.transpose(Matriz_A)

array([[ 5,  6,  4],
       [ 8,  9,  7],
       [-4, -5, -2]])

* 5.3 Crear un vector A con la primera fila de la matriz A y un vector B con la ultima fila de la matriz A.

In [51]:
Vector_A = Matriz_A[0,:] # vector con la primera fila de la matriz A
Vector_B = Matriz_A[:,0] # vector con la primera columan de la matriz A

print(Vector_A)
print(Vector_B)

[ 5  8 -4]
[5 6 4]


In [ ]:
Vector_C = Matriz_A[1,2] # ??
# print(Vector_C)

* 5.4 Calcular el producto punto entre los vectores recién creados. Multiplicación de Vectores

Para multiplicar 2 vectores o 2 matrices se puede utilizar la función **.dot** que corresponde a la libreria de numpy

In [21]:
Producto_Punto = Vector_A.dot(Vector_B)
print(Vector_A)
print(Vector_B)
print(Producto_Punto)

[ 5  8 -4]
[5 6 4]
57


* 5.5 Multiplique la matriz A con la matriz A Transpuesta

In [52]:
Matriz_A.dot(Matriz_A.T)

array([[105, 122,  84],
       [122, 142,  97],
       [ 84,  97,  69]])

* 5.6 Calcule el número de fila y columnas de la matriz A

In [64]:
Numerofilas= Matriz_A.shape[1] #filas 
print(Numerofilas)

NumeroColumnas = Matriz_A.shape[0] #columnas
print(NumeroColumnas)

3
3


* 5.7 Sumar las columnas de la matriz A

In [65]:
Matriz_A.sum(axis=0) #columnas

array([ 15,  24, -11])

### 6. Trabajando con Matrices - Broadcasting

https://numpy.org/doc/stable/user/basics.broadcasting.html#:~:text=The%20term%20broadcasting%20describes%20how,that%20they%20have%20compatible%20shapes.&text=NumPy%20operations%20are%20usually%20done,element%2Dby%2Delement%20basis.

(m,n) + - * /  (1,n)  -->  (m,n)


(m,n) + - * /  (m,1)  -->  (m,n)

**reshape(m,n)** permite tener CERTEZA de que la matriz/vector tiene esa composición

In [66]:
test = np.array([5, 8, -4]).reshape(3,1)

In [67]:
test * 100

array([[ 500],
       [ 800],
       [-400]])

#### Tip

In [68]:
#Creamos el vector B
Vect_B = np.array([4,8,2])
print(Vect_B)


[4 8 2]


In [73]:
# ¿Qué ocurre son la Traspuesta?
print(Vect_B.T)

[4 8 2]


In [84]:
# Creamos el vector C
Vect_C = np.array([4,8,2]).reshape(1,3)
print(Vect_C)

[[4 8 2]]


In [77]:
print(Vect_C.T)

[[4]
 [8]
 [2]]


In [78]:
# Veamos como se componen
print(Vect_B.shape)
print(Vect_C.shape)

(3,)
(1, 3)


In [90]:
# Multicplicamos vector_B con su respectiva transpuesta
np.dot(Vect_B.T,Vect_B)

84

In [91]:
# Multicplicamos vector_C con su respectiva transpuesta
np.dot(Vect_C.T,Vect_C)

array([[16, 32,  8],
       [32, 64, 16],
       [ 8, 16,  4]])

Por un lado generamos una estructura de datos con el vector B formado como (3,) matriz denominada "Matriz de Rango 1", que no se comporta ni como vector fila, ni como vector columna.

Se recomienda armar vectores de columnas o vectores de filas, tal como el vector C.

### 7. Loop For


* Seguimos trabajando en base a la misma matriz A:

    $$
    A = \begin{pmatrix}
    5 & 8 & -4 \\
    6 & 9 & -5\\
    4 & 7 & -2
    \end{pmatrix}
    $$

In [118]:
range(Numerofilas)
range(NumeroColumnas)

range(0, 3)

* 7.1 Obtener mediante un Loop la columna de al medio de la matriz A

In [94]:
lista = [] # creamos una lista vacia

for j in range(Numerofilas):
         lista.append(Matriz_A[j,1]) # El método append() agrega un elemento al final de la lista.

lista

[8, 9, 7]

* 7.2 Obtener mediante un Loop anidado todos los números dentro de la matriz A

In [95]:
for s in range(NumeroColumnas):  #Recorremos las columnas
    for k in range(Numerofilas): #Recorremos las filas
        print(Matriz_A[k , s])

5
6
4
8
9
7
-4
-5
-2


### Desafio!
* 7.3 Dibuja mediante Loops la matriz A, donde se pueda visualizar cada fila con sus respectivos valores

In [117]:
lista2 = []

for k in range(Numerofilas):
    for j in range(NumeroColumnas):
         lista2.append(Matriz_A[k,j])
    print(lista2)
    lista2 = []

[5, 8, -4]
[6, 9, -5]
[4, 7, -2]
